name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./webcv

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

#      - name: Install dependencies
#        working-directory: ${{ env.working-directory }}
#        run: yarn install --ignore-scripts

      - name: Generate
        working-directory: ${{ env.working-directory }}
        run: yarn run generate
        env:
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          CMS_API_KEY: ${{ secrets.CMS_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webcv/dist

