name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./webcv

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-webcv-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-webcv-

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install --ignore-scripts

      - name: Generate
        working-directory: ${{ env.working-directory }}
        run: yarn run generate
        env:
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          CMS_API_KEY: ${{ secrets.CMS_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webcv/dist
          cname: ${{ secrets.SITE_URL }}
